---
- name: GRAB F5 INFO
  hosts: f5
  connection: local
  gather_facts: no


  tasks:

    - name: COLLECT BIG-IP INFO
      bigip_device_info:
        gather_subset:
          - virtual-addresses
          - system-info


        provider:
          server: "{{F5_SERVER}}"
          user: "{{F5_USER}}"
          password: "{{F5_PASSWORD}}"
          server_port: "{{F5_SERVER_PORT}}"
          validate_certs: no
      register: device_info

    - name: DISPLAY COMPLETE BIG-IP SYSTEM INFORMATION
      debug:
        var: device_info

    - name: DISPLAY ONLY THE MAC ADDRESS
      debug:
        var: device_info['system_info']['base_mac_address']

    - name: DISPLAY ONLY THE VERSION
      debug:
        var: device_info['system_info']['product_version']
